steps:
- name: '<YOUR-REGISTRY>/<YOUR-REPO>/<KANIKO-EXECUTOR>'
  args:
  - --build-arg=NUM=${_COUNT}
  - --no-push
  - --snapshot-mode=redo
  env:
  - 'BENCHMARK_FILE=gs://$PROJECT_ID/gcb/benchmark_file_${_COUNT}'
  timeout: 2400s
timeout: 2400s
substitutions:
  _COUNT: "10000" # default value