FROM busybox
RUN <<EOF
touch /tmp/bli
touch /tmp/bla
touch /tmp/blubb
ls -la /tmp
EOF
RUN ls -la /kaniko
RUN ls -la /tmp

RUN cat <<file1.txt <<file2.txt > /tmp/file1.txt
Hello from file1
file1.txt
Hello from file2
file2.txt
RUN ls -la /tmp && cat /tmp/file1.txt
