name: Build images

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

permissions: {}

jobs:
  build-images:
    concurrency:
      # If a previous run is ongoing with the same head_ref (it's a run on the
      # same PR) then cancel it to save time. If it isn't a PR, only cancel the
      # previous run if it's on the same commit SHA. This prevents a run for a
      # commit push from cancelling a previous commit push's build, since we
      # want an image built and tagged for each commit.
      group: build-images-${{ matrix.image }}-${{ github.head_ref || github.sha }}
      cancel-in-progress: true

    permissions:
      contents: read  # Read the repo contents.
      id-token: write  # Produce identity token for keyless signing.

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
          - linux/s390x
          - linux/ppc64le

        include:
          - platform: linux/amd64
            arch: amd64
            targets: executor,debug,slim,warmer,bootstrap

          - platform: linux/arm64
            arch: arm64 
            targets: executor,debug,slim,warmer,bootstrap

          - platform: linux/s390x
            arch: s390x 
            targets: executor,debug,slim,warmer,bootstrap

          - platform: linux/ppc64le
            arch: ppc64le 
            targets: executor,slim,warmer

    env:
      REGISTRY: martizih/kaniko
      TAG: ${{ github.sha }}-${{ matrix.platform }}
      
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Setup auth if not a PR.
      - if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push with Docker.
      - uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
        with:
          platforms: ${{ matrix.platform }}

      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - uses: docker/bake-action@37816e747588cb137173af99ab33873600c46ea8 # v6.8.0
        with:
          source: .
          push: false
          set: |
            *.platforms=${{ matrix.platform }}

  merge-manifests:
    needs: build-images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image:
          - executor
          - executor-debug
          - executor-slim
          - warmer
          - bootstrap

        include:
          - image: executor
            target: kaniko-executor
            platforms: amd64,arm64,s390x,ppc64le
            image-name: martizih/kaniko
            tag: ${{ github.sha }}
            release-tag: latest

          - image: executor-debug
            target: kaniko-debug
            platforms: amd64,arm64,s390x
            image-name: martizih/kaniko
            tag: ${{ github.sha }}-debug
            release-tag: debug

          - image: executor-slim
            target: kaniko-slim
            platforms: amd64,arm64,s390x,ppc64le
            image-name: martizih/kaniko
            tag: ${{ github.sha }}-slim
            release-tag: slim

          - image: warmer
            target: kaniko-warmer
            platforms: amd64,arm64,s390x,ppc64le
            image-name: martizih/kaniko
            tag: ${{ github.sha }}-warmer
            release-tag: warmer

          - image: bootstrap
            target: kaniko-debug-2
            platforms: amd64,arm64,s390x,ppc64le
            image-name: martizih/kaniko
            tag: ${{ github.sha }}-bootstrap
            release-tag: bootstrap

    steps:
      - uses: imjasonh/setup-crane@31b88efe9de28ae0ffa220711af4b60be9435f6e # v0.4

      - name: Merge images with crane
        run: |
          IFS=',' read -ra platforms <<< "${{ matrix.platforms }}"
          manifests=()
          for platform in "${platforms[@]}"; do
            manifests+=(--manifest ${{ matrix.image-name }}:${{ github.sha }}-${ platform }-${{ matrix.release-tag }})
          done
          crane manifest append "${manifests[@]}" --tag ${{ matrix.image-name }}:${{ github.sha }}-${{ matrix.release-tag }}
          for platform in "${platforms[@]}"; do
            crane manifest rm ${{ matrix.image-name }}:${{ github.sha }}-${platform}-${{ matrix.release-tag }}
          done
      # Sign images if not a PR.
      - if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@398d4b0eeef1380460a10c8013a76f728fb906ac # v3.9.1
      - if: github.event_name != 'pull_request'
        run: |
          cosign sign --yes \
              ${{ matrix.image-name }}@${{ steps.build-and-push.outputs.digest }}

      # If a tag push, use crane to add more tags.
      - if: startsWith(github.ref, 'refs/tags/v')
        uses: imjasonh/setup-crane@31b88efe9de28ae0ffa220711af4b60be9435f6e # v0.4
      - if: startsWith(github.ref, 'refs/tags/v')
        name: Apply release tags
        run: |
          tag=${GITHUB_REF/refs\/tags\//}

          # Tag :latest, :debug, :slim
          crane cp ${{ matrix.image-name }}@${{ steps.build-and-push.outputs.digest }} \
              ${{ matrix.image-name }}:${{ matrix.release-tag }}

          if [[ "${{ matrix.release-tag }}" == "latest" ]]; then
            # Tag :latest images as :v1.X.Y
            crane cp ${{ matrix.image-name }}@${{ steps.build-and-push.outputs.digest }} \
                ${{ matrix.image-name }}:${tag}
          else
            # Or tag :v1.X.Y-debug and :v1.X.Y-slim
            crane cp ${{ matrix.image-name }}@${{ steps.build-and-push.outputs.digest }} \
                ${{ matrix.image-name }}:${tag}-${{ matrix.release-tag }}
          fi
