name: Integration tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

permissions: {}

jobs:
  tests:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      IMAGE_REPO: 'localhost:5000'
      REGISTRY: 'localhost:5000'
      PROXY: 'localhost:5001'
      DOCKER_BUILDKIT: '1'

    strategy:
      fail-fast: false
      matrix:
        make-target:
          - integration-test-layers
          - integration-test-misc
          - integration-test-run
          - k8s-executor-build-push integration-test-k8s

    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@90e01b21170618765a73370fcc3abbd1684a7793 # v5
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: '1.25.0'
          check-latest: true

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        with:
          buildkitd-config-inline: |
            [registry."docker.io"]
              mirrors = ["${PROXY}"]

      - run: make install-diffoci k3s-setup
      - run: make ${{ matrix.make-target }}
