name: Integration tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

permissions: {}

jobs:
  tests:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      IMAGE_REPO: 'localhost:5000'
      REGISTRY: 'localhost:5000'
      DOCKER_BUILDKIT: '1'

    strategy:
      fail-fast: false
      matrix:
        include:
          - make-target: integration-test-layers
            make-setup: install-diffoci
          - make-target: integration-test-misc
            make-setup: install-diffoci
          - make-target: integration-test-run
            make-setup: install-diffoci
          - make-target: k8s-executor-build-push integration-test-k8s
            make-setup: install-diffoci k3s-setup

    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@90e01b21170618765a73370fcc3abbd1684a7793 # v5
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: '1.24'
          check-latest: true

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - run: make ${{ matrix.make-setup }}
      - run: make ${{ matrix.make-target }}
